### PR TITLE
Add X10D.ReExposed

### PR DESCRIPTION
**Pull request by Redageddon**
This is something i had in my project, it is where i just reexposed existing methods as extensions EX: 
`public static bool ToBool(this string value)
{
    return bool.Parse(value);
}`
You had some instances of this in your own code which i removed because i already have it in mine. 
My idea was that this should be its own package because some people may not want reexposed methods in X10D, so that is the reason as to why i made it a new project instead of adding it.    
This is how i handled it in my own project: 
-must only reexpose methods (IE cannot introduce custom logic) the only exceptions being for nullability overloading and basic casting, or something like that
-does not need to be tested, it is just recalling existing methods, if it needs to be tested for whatever reason, then it should not be an extension that is part of reexposed,
-must call the documentation of the base object
-paramaters must be the same name, becuase of the doc copy

### CODE REVIEW

**Comment by oliverbooth** [comment]
I will need to review this code later, as I've just woken up. There's a lot of files to check. But can you explain some things?
You say you want this to be its own package yet you have removed a lot of code from the base X10D library. Why is that?

And I'm not sure what you mean by:
> some people may not want reexposed methods in X10D

Extension methods are opt-in by the namespace they live in, consumers do not have to use them if they don't want to.

**Comment by Redageddon** [comment]
> yet you have removed a lot of code from the base X10D library. Why is that?
bb111975b2577108debbbdc25d53ece2c5fa6ec1

**Comment by Redageddon** [comment]
> Extension methods are opt-in by the namespace they live in, consumers do not have to use them if they don't want to.

The clutter or reexposed methods being reccomended by the ide may be annoying who doesnt want to use them reexposed. Plus having it as a different project makes it extremely easy to differentiate exposed from non exposed code

**Comment by oliverbooth** [comment]
I'm not sure I agree with the premise of migrating a huge chunk of existing functionality to a new package. This would be a fundamental breaking change to the entire CI workflow.

I'll review your changes properly and come to a decision on how best to proceed

**Comment by Redageddon** [comment]
> I'm not sure I agree with the premise of migrating a huge chunk of existing functionality 

Its not a huge chunk tho, 4 classes, and 23 unique methods

**Pull request closed without merging**
